# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-FTPSSL
version:      0.22
version_from: FTPSSL.pm
installdirs:  site
requires:
    File::Basename:                0
    File::Copy:                    0
    IO::Socket::SSL:               1.08
    Net::SSLeay::Handle:           0
    Sys::Hostname:                 0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
