# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-FTPSSL
version:      0.04
version_from: FTPSSL.pm
installdirs:  site
requires:
    IO::Socket::SSL:               0
    Net::SSLeay::Handle:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
